<button class="emoji" data-emoji="😊">😊</button>
<button class="emoji" data-emoji="😂">😂</button>
<button class="emoji" data-emoji="😍">😍</button>
<button class="emoji" data-emoji="😎">😎</button>
<button class="emoji" data-emoji="😅">😅</button>
<button class="emoji" data-emoji="😜">😜</button>
<button class="emoji" data-emoji="😇">😇</button>
<button class="emoji" data-emoji="🤩">🤩</button>
<button class="emoji" data-emoji="🥺">🥺</button>
<button class="emoji" data-emoji="🥳">🥳</button>
<button class="emoji" data-emoji="🤗">🤗</button>
<button class="emoji" data-emoji="😻">😻</button>
<button class="emoji" data-emoji="😋">😋</button>
<button class="emoji" data-emoji="😜">😜</button>
<button class="emoji" data-emoji="😌">😌</button>
<button class="emoji" data-emoji="😉">😉</button>
<button class="emoji" data-emoji="😆">😆</button>
<button class="emoji" data-emoji="😃">😃</button>
<button class="emoji" data-emoji="😄">😄</button>
<button class="emoji" data-emoji="😱">😱</button>
<button class="emoji" data-emoji="😴">😴</button>
<button class="emoji" data-emoji="😧">😧</button>
<button class="emoji" data-emoji="😮">😮</button>
<button class="emoji" data-emoji="😲">😲</button>
<button class="emoji" data-emoji="😵">😵</button>
<button class="emoji" data-emoji="🥲">🥲</button>
<button class="emoji" data-emoji="😶">😶</button>
<button class="emoji" data-emoji="😏">😏</button>
<button class="emoji" data-emoji="😬">😬</button>
<button class="emoji" data-emoji="😑">😑</button>
<button class="emoji" data-emoji="😒">😒</button>
<button class="emoji" data-emoji="🥱">🥱</button>
<button class="emoji" data-emoji="🙄">🙄</button>
<button class="emoji" data-emoji="🤔">🤔</button>
<button class="emoji" data-emoji="🤭">🤭</button>
<button class="emoji" data-emoji="😶‍🌫️">😶‍🌫️</button>
<button class="emoji" data-emoji="🫣">🫣</button>
<button class="emoji" data-emoji="🫤">🫤</button>
<button class="emoji" data-emoji="🙃">🙃</button>
<button class="emoji" data-emoji="😺">😺</button>
<button class="emoji" data-emoji="😸">😸</button>
<button class="emoji" data-emoji="😹">😹</button>
<button class="emoji" data-emoji="😻">😻</button>
<button class="emoji" data-emoji="😼">😼</button>
<button class="emoji" data-emoji="😽">😽</button>
<button class="emoji" data-emoji="🙀">🙀</button>
<button class="emoji" data-emoji="😿">😿</button>
<button class="emoji" data-emoji="😾">😾</button>
<button class="emoji" data-emoji="🫶">🫶</button>
<button class="emoji" data-emoji="🤲">🤲</button>
<button class="emoji" data-emoji="🙏">🙏</button>
<button class="emoji" data-emoji="🤝">🤝</button>
<button class="emoji" data-emoji="👌">👌</button>
<button class="emoji" data-emoji="🤌">🤌</button>
<button class="emoji" data-emoji="✌️">✌️</button>
<button class="emoji" data-emoji="🤘">🤘</button>
<button class="emoji" data-emoji="🤙">🤙</button>
<button class="emoji" data-emoji="🤯">🤯</button>
<button class="emoji" data-emoji="🥴">🥴</button>
<button class="emoji" data-emoji="😵‍💫">😵‍💫</button>
<button class="emoji" data-emoji="🤐">🤐</button>
<button class="emoji" data-emoji="🫠">🫠</button>
<button class="emoji" data-emoji="🫤">🫤</button>
<button class="emoji" data-emoji="💀">💀</button>
<button class="emoji" data-emoji="👻">👻</button>
<button class="emoji" data-emoji="👽">👽</button>
<button class="emoji" data-emoji="👾">👾</button>
<button class="emoji" data-emoji="💩">💩</button>
<button class="emoji" data-emoji="🥳">🥳</button>
<button class="emoji" data-emoji="🦸‍♂️">🦸‍♂️</button>
<button class="emoji" data-emoji="🦸‍♀️">🦸‍♀️</button>
<button class="emoji" data-emoji="🦹‍♂️">🦹‍♂️</button>
<button class="emoji" data-emoji="🦹‍♀️">🦹‍♀️</button>
<button class="emoji" data-emoji="🧙‍♂️">🧙‍♂️</button>
<button class="emoji" data-emoji="🧙‍♀️">🧙‍♀️</button>
<button class="emoji" data-emoji="🧝‍♂️">🧝‍♂️</button>
<button class="emoji" data-emoji="🧝‍♀️">🧝‍♀️</button>
<button class="emoji" data-emoji="🧛‍♂️">🧛‍♂️</button>
<button class="emoji" data-emoji="🧛‍♀️">🧛‍♀️</button>
<button class="emoji" data-emoji="🧞‍♂️">🧞‍♂️</button>
<button class="emoji" data-emoji="🧞‍♀️">🧞‍♀️</button>
<button class="emoji" data-emoji="🧟‍♂️">🧟‍♂️</button>
<button class="emoji" data-emoji="🧟‍♀️">🧟‍♀️</button>
<button class="emoji" data-emoji="🦄">🦄</button>
<button class="emoji" data-emoji="🐉">🐉</button>
<button class="emoji" data-emoji="🦖">🦖</button>
<button class="emoji" data-emoji="🦧">🦧</button>
<button class="emoji" data-emoji="🦦">🦦</button>
<button class="emoji" data-emoji="🐅">🐅</button>
<button class="emoji" data-emoji="🐆">🐆</button>
<button class="emoji" data-emoji="🐈">🐈</button>
<button class="emoji" data-emoji="🐎">🐎</button>
<button class="emoji" data-emoji="🐄">🐄</button>
<button class="emoji" data-emoji="🐏">🐏</button>
<button class="emoji" data-emoji="🐖">🐖</button>
<button class="emoji" data-emoji="🐗">🐗</button>
<button class="emoji" data-emoji="🐶">🐶</button>
<button class="emoji" data-emoji="🐕">🐕</button>

<!-- Love Emojis -->
<button class="emoji" data-emoji="💖">💖</button>
<button class="emoji" data-emoji="💘">💘</button>
<button class="emoji" data-emoji="💝">💝</button>
<button class="emoji" data-emoji="💓">💓</button>
<button class="emoji" data-emoji="❤️">❤️</button>
<button class="emoji" data-emoji="💗">💗</button>
<button class="emoji" data-emoji="💙">💙</button>
<button class="emoji" data-emoji="💚">💚</button>
<button class="emoji" data-emoji="💛">💛</button>
<button class="emoji" data-emoji="💜">💜</button>

<!-- Repeat the above set multiple times until it reaches 500 -->
